project_identifier: advanced-peripherals
base_path: .
files:
  - source: /src/generated/resources/assets/advancedperipherals/lang/en_us.json
    translation: /src/main/resources/assets/advancedperipherals/lang/%locale_with_underscore%.json
