modLoader = "javafml"
loaderVersion = "[43,)"
license = "Apache-2.0 license"
issueTrackerURL = "https://github.com/Seniorendi/AdvancedPeripherals/issues"
logoFile = "pack.png"

[[mods]]
modId = "advancedperipheralstest"
version = "1.0.0"
displayName = "CC: Tweaked test framework"
description = '''
A test framework for ensuring AP works correctly. Copied from CC:T code
'''
